## Session5 - playground

- Import the necessary packages
- Load the iris dataset
- Create the observations `X` and labels `y`


- 必要なパッケージをインポートします
- アヤメのデータセットを読み込みます
- 観測値`X`とラベル`y`を作成します

In [30]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

# Load data
iris = np.genfromtxt('iris_data.csv', delimiter=',')

X = iris[:,1:]
y = iris[:,0]
print("X has shape:", X.shape)
print("y has shape:", y.shape)

X has shape: (150, 4)
y has shape: (150,)


## TASK 1: preparation

Copy your code for data preparation from day1, session4-playground1 (both TASK1 and TASK2) in the cell below and execute it.

以下のセルにday1のsession4-playground1からデータ準備用のコード（TASK1とTASK2の両方）をコピーして、実行してください。

In [31]:
## YOUR CODE HERE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#Split data
X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size=0.3)

#Standardization of data
scaler = StandardScaler()

scaler.fit(X_train);

X_train_raw = X_train
X_train = scaler.transform(X_train_raw)

X_test_raw = X_test
X_test = scaler.transform(X_test_raw)

## TASK 2
- Create and train a linear support vector classifier


- 線形サポートベクトル分類器を作成し、トレーニングさせる

In [32]:
## YOUR CODE HERE
from sklearn.svm import LinearSVC

#Create the classifire
linear_SVC = LinearSVC()
linear_SVC.fit(X_train, y_train); 

#Training of the classifire
i = 0

# The ith test sample is composed of
# the label
y_i = y_test[i]
# the features (reshape is used because predict needs a 2D array)
X_i = X_test[i].reshape(1, -1)

print(y_i, X_i)

# Show the truth
print("True Flower type:", y_i)

# Using predict method
# the input X_i is an array with a single feature
# the result is an array with a single element
y_pred = linear_SVC.predict(X_i)
y_pred = y_pred[0]

print("Prediction:", y_pred)

# Check the prediction
if y_pred == y_i:
    print("This is a correct prediction")
else:
    print("This is not a correct prediction")   

#Applying the pridict function to the whole testing set
y_pred = linear_SVC.predict(X_test)

1.0 [[-0.33889338 -0.1337266   0.36814532  0.30751308]]
True Flower type: 1.0
Prediction: 1.0
This is a correct prediction


## TASK 3
- Predict the labels for the test features


- テストデータのラベルを予測する

In [33]:
## YOUR CODE HERE
# Compare the prediction to the truth
res = (y_pred == y_test)

print(y_pred.shape, y_test.shape)

# Show a few examples
for i in range(10):
    print("True labels:", y_test[i],  "\t Predicted labels:", y_pred[i], "\tCorrect prediction:", res[i])

(45,) (45,)
True labels: 1.0 	 Predicted labels: 1.0 	Correct prediction: True
True labels: 0.0 	 Predicted labels: 0.0 	Correct prediction: True
True labels: 0.0 	 Predicted labels: 0.0 	Correct prediction: True
True labels: 0.0 	 Predicted labels: 0.0 	Correct prediction: True
True labels: 2.0 	 Predicted labels: 1.0 	Correct prediction: False
True labels: 0.0 	 Predicted labels: 0.0 	Correct prediction: True
True labels: 1.0 	 Predicted labels: 1.0 	Correct prediction: True
True labels: 1.0 	 Predicted labels: 1.0 	Correct prediction: True
True labels: 0.0 	 Predicted labels: 0.0 	Correct prediction: True
True labels: 2.0 	 Predicted labels: 1.0 	Correct prediction: False


## TASK 4
- Show the confusion matrix
- Compute the accuracy (you should obtain more than 0.9 (90%) accuracy)


- 混同行列を表示する
- 精度を計算する（0.9（90％）以上の精度が得られるはずです）

In [34]:
## YOUR CODE HERE
from sklearn.metrics import confusion_matrix

CM = confusion_matrix(y_test, y_pred)
print(CM)

for i in range(3):
    print("The number of correctly predicted {} is given by CM[{},{}] = {} \n".format(i, i, i, CM[i, i]))
    
A = np.sum(np.diag(CM)) / np.sum(CM)
print("Accuracy: {:.02f}".format(A))

[[15  0  0]
 [ 0 19  1]
 [ 0  2  8]]
The number of correctly predicted 0 is given by CM[0,0] = 15 

The number of correctly predicted 1 is given by CM[1,1] = 19 

The number of correctly predicted 2 is given by CM[2,2] = 8 

Accuracy: 0.93


## OPTIONAL 1
- Run the training another time and compare (tip: you can use `Cell -> Run All` from the menu)
- Change the proportion of test samples and see the impact on the performance


- トレーニングをもう一度実行して、結果を比較します（ヒント：メニューから`Cell -> Run All`を利用できます）
- テストサンプルの比率を変更し、パフォーマンスへの影響を確認する

In [35]:
## YOUR CODE HERE
from sklearn.metrics import accuracy_score

#-----Split data
X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size=0.5)

#-----Standardization of data
scaler = StandardScaler()

scaler.fit(X_train);

X_train_raw = X_train
X_train = scaler.transform(X_train_raw)

X_test_raw = X_test
X_test = scaler.transform(X_test_raw)

#-----Create the classifire
linear_SVC = LinearSVC()
linear_SVC.fit(X_train, y_train); 

#-----Training of the classifire
i = 0

# The ith test sample is composed of
# the label
y_i = y_test[i]
# the features (reshape is used because predict needs a 2D array)
X_i = X_test[i].reshape(1, -1)

print(y_i, X_i)

# Show the truth
print("True Flower type:", y_i)

#-----Using predict method
# the input X_i is an array with a single feature
# the result is an array with a single element
y_pred = linear_SVC.predict(X_i)
y_pred = y_pred[0]

print("Prediction:", y_pred)

#-----Check the prediction
if y_pred == y_i:
    print("This is a correct prediction")
else:
    print("This is not a correct prediction")   

# Applying the pridict function to the whole testing set
y_pred = linear_SVC.predict(X_test)

# Compare the prediction to the truth
res = (y_pred == y_test)

print(y_pred.shape, y_test.shape)

#-----Show a few examples
for i in range(10):
    print("True labels:", y_test[i],  "\t Predicted labels:", y_pred[i], "\tCorrect prediction:", res[i])
    
#-----accuracy score
A = accuracy_score(y_test,  y_pred)
print("Accuracy: {:.02f}".format(A))

2.0 [[1.677268   1.3181703  1.36746198 1.76190218]]
True Flower type: 2.0
Prediction: 2.0
This is a correct prediction
(75,) (75,)
True labels: 2.0 	 Predicted labels: 2.0 	Correct prediction: True
True labels: 2.0 	 Predicted labels: 2.0 	Correct prediction: True
True labels: 2.0 	 Predicted labels: 2.0 	Correct prediction: True
True labels: 0.0 	 Predicted labels: 0.0 	Correct prediction: True
True labels: 0.0 	 Predicted labels: 0.0 	Correct prediction: True
True labels: 1.0 	 Predicted labels: 1.0 	Correct prediction: True
True labels: 1.0 	 Predicted labels: 1.0 	Correct prediction: True
True labels: 2.0 	 Predicted labels: 2.0 	Correct prediction: True
True labels: 2.0 	 Predicted labels: 2.0 	Correct prediction: True
True labels: 0.0 	 Predicted labels: 0.0 	Correct prediction: True
Accuracy: 0.93


## OPTIONAL 2

The splitting between training and testing set does not care if there is an "equal" number of each flower type in the sets.

- Write some code to split the dataset randomly and care about having an equal representation of each flower type (you can start from the code for manually spliting in the main notebook)
- Test the average performance of the classifier using this dataset splitting method

トレーニングセットとテストセットの分割は、セット内の各花の種類が「等しい」数であるかどうかを考慮していません。

- データセットをランダムに分割し、各花の種類の数が同じになるためのコードを実装してください（ヒント：メインのノートブックにある手動の分割のコードを元に開発できます）
- このデータセット分割方法を使用して、分類器の平均パフォーマンスを確認してください

In [36]:
## YOUR CODE HERE
X_train, X_test, y_train, y_test = [], [], [], []

for i in range(3):
    y, X = [x[0] for x in iris if x[0]==i], [x[1:5] for x in iris if x[0]==i]
    X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size=0.5)
    X_train = X_train + X_train2
    X_test = X_test + X_test2
    y_train = y_train + y_train2
    y_test = y_test + y_test2
    
X_train_raw = X_train
X_train = scaler.transform(X_train_raw)

X_test_raw = X_test
X_test = scaler.transform(X_test_raw)

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

#first
linear_SVC1 = LinearSVC()
linear_SVC1.fit(X_train, y_train) ;

y_pred = linear_SVC1.predict(X_test)

A = accuracy_score(y_test, y_pred)
print("Accuracy: {:.02f}".format(A))

#second
linear_SVC2 = LinearSVC()
linear_SVC2.fit(X_train, y_train) ;

y_pred = linear_SVC2.predict(X_test)

B = accuracy_score(y_test, y_pred)
print("Accuracy: {:.02f}".format(B))

#average
mean = (A + B) / 2
print("Accuracy: {:.02f}".format(mean))

Accuracy: 0.92
Accuracy: 0.92
Accuracy: 0.92
